### PR TITLE
Install Linux development packages

### PR DESCRIPTION
**Pull request by dellis1972**
Context : https://github.com/kcat/openal-soft/issues/717

We got a bug report on Linux with the following error "Could not open /dev/dsp". 
Its because we did not install the required development libraries when building the linux build. 
Lets fix that.

### CODE REVIEW

**Comment by Vectovox** [comment]
I guess I should have made an issue already yesterday, but here is an update after trying the lib artifact built from this PR.

**System (would test more configs but this still showed regression):**
- SteamDeck (non-OLED)
- SteamOS 3.6.20

**Tests:**
- ✔️ Runs fine when running the executable directly. The new lib fixed this, as it didn't work before.
- ❌ Error on SteamOS if launching the executable via Steam. _"Error reading audio: Failed to init OpenALSoundController"_. This wasn't the case with previous MG versions, and using the old openal.so.1 (renamed to openal.so) gets everything working again. So, there definitely seems to be something related to the build still. Though why it's only through Steam I can't say, as I'm rather novice in this area.

**Comment by ThomasFOG** [comment]
Do we have any trace from building the binary? I guess the makefile should tell toward which audio backends it builds or if some are missing.

**Comment by dellis1972** [comment]
> Do we have any trace from building the binary? I guess the makefile should tell toward which audio backends it builds or if some are missing.

The logs show we are building with 

```
Building OpenAL with support for the following backends:
--     PipeWire, PulseAudio, ALSA, OSS, SndIO (linked), JACK, PortAudio, WaveFile, Null
```

The issue is the it doesn't work when launched from the Steam client, but when run manually from a terminal it does.

**Comment by Vectovox** [comment]
I ran some tests on Ubuntu 24.04 as well.

**System**
- Dell XPS13 (2016 or so)
- Ubuntu 24.04

It doesn't work at all with the latest build. Neither through Steam nor launching an application manually.

Replacing back the old MG .so.1 file (renamed of course) works in all cases. Both Ubuntu as well as SteamOS, both through Steam and manually executing.

For reference, I'm testing with --self-contained builds.

**Comment by dellis1972** [comment]
@Vectovox can you run `ldd libopenal.so` to figure out if there are any missing dependencies?

**Comment by Vectovox** [comment]
> @Vectovox can you run `ldd libopenal.so` to figure out if there are any missing dependencies?

I get what seems to be one missing lib on both Ubuntu and SteamOS:
- libsndio.so.7

**Comment by Vectovox** [comment]
For reference here is the full list:

- linux-vdso.so.1 (0x00007ffefd1ce000)
- libsndio.so.7 => not found
- libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x0000795e1c200000)
- libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x0000795e1c517000)
- libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x0000795e1c4f7000)
- libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x0000795e1be00000)
- /lib64/ld-linux-x86-64.so.2 (0x0000795e1c7a4000)

And here is the list from the old library:
- linux-vdso.so.1 (0x00007fff57941000)
- librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007e4dbe4ea000)
- libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007e4dbe4e5000)
- libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007e4dbe4e0000)
- libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007e4dbe3f9000)
- libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007e4dbdc00000)
- /lib64/ld-linux-x86-64.so.2 (0x00007e4dbe500000)

**Comment by Vectovox** [comment]
I can confirm the latest build works on Ubuntu and SteamOS, launching both manually and via Steam.

Well done!

**Pull request merged**
